### ISSUE TITLE
Randomize position

### ISSUE THREAD

**Issue by anmamtl** [bigbhowell/photopile-js#6]
Hello ;)

Thank you for this script!
I have set my setting to 0 rotation, and as a result all the images in a row are align from the bottom.
I was wondering if there was a way in your script to randomize the position so that all image a really all spilled everywhere, with 0 rotation?

Thank you ;)

**Comment by bigbhowell** [comment]
Hello. I'm not doing any more development on this project and haven't been for some time, but thanks for the feedback.
