### ISSUE TITLE
Feature: start auto play on event?

### ISSUE THREAD

**Issue by NickSutton** [bigbhowell/photopile-js#7]
Hi, how about being able to kick in the auto play feature for a time until you want to turn it off?

Almost like a screensaver, but without having to alter the configuration file?

**Comment by lavermil** [comment]
Maybe I don't understand what the autoplay feature is, but my thoughts is that autoplay feature would every so many ms pick a picture programmatically click on it, thus showing the full image. I might just test a piece of javascript outside his code to see if it works.

**Comment by bigbhowell** [comment]
Hey guys I'm not doing any more development on this project and haven't been for some time, but thanks for the feedback.
